import {
    attribute,
    autoGeneratedHashKey,
    table,
  } from '@aws/dynamodb-data-mapper-annotations'
  import { BaseModel } from './base.model'
  import { getSecondsSinceEpoch } from '../utils/common'
  import config from '../config'
  
  const SSO_SESSION_TTL_IN_SECONDS = config.get('ttl').ssoSession
  @table('sso-session')
  export class SsoSession extends BaseModel {
    @autoGeneratedHashKey()
    uuid: string
  
    /**
    * String that represents the End-User's login state at the OP. It MUST NOT contain 
    * the space (" ") character. This value is opaque to the RP.
    *
    * See https://openid.net/specs/openid-connect-session-1_0.html for more info
    */
    @attribute()
    sessionState: string
  
    @attribute({
      defaultProvider: () => getSecondsSinceEpoch() + SSO_SESSION_TTL_IN_SECONDS,
    }) // 5 mins
    ttl: number
  }